### ISSUE TITLE
Light theme seems a bit broken visually

### ISSUE THREAD

**Issue by andreigabreanu** [shahidshaikhs/Tailwind-Cheat-Sheet-Chrome-Extension#1]
Hi,
It seems the extension is a bit broken visually when using a light theme. Attached are 2 screenshots to see how it looks on a light theme.

![Screenshot 2022-06-28 at 12 38 05](https://user-images.githubusercontent.com/3910702/176147277-1f18ba87-e8f8-4b0b-b34c-a8f410ba0398.png)
![Screenshot 2022-06-28 at 12 37 55](https://user-images.githubusercontent.com/3910702/176147284-55f6370a-07aa-496b-b66f-ddd22694d2f5.png)

**Comment by shahidshaikhs** [comment]
Thank you @andreigabreanu for pointing out this issue. 

I have now resolved the same. Do let me know in case you're still facing issues.
